import 'dart:io';

import 'package:mason/mason.dart';

/// Runs a command and reports progress, returning whether it succeeded.
Future<bool> _run(
  HookContext context,
  String label,
  String executable,
  List<String> args,
) async {
  final progress = context.logger.progress(label);
  try {
    final result = await Process.run(executable, args, runInShell: true);
    if (result.exitCode == 0) {
      progress.complete('$label — done');
      return true;
    }
    progress.fail('$label — failed (exit ${result.exitCode})');
    context.logger.detail('stdout: ${result.stdout}');
    context.logger.err('stderr: ${result.stderr}');
    return false;
  } catch (e) {
    progress.fail('$label — error: $e');
    return false;
  }
}

void run(HookContext context) async {
  context.logger.info('Post generation started');

  // Dependencies are now pinned in pubspec.yaml, so we only need to resolve
  // them — no `dart pub add` step is required anymore.
  if (!await _run(context, 'Getting packages', 'flutter', ['pub', 'get'])) {
    return;
  }

  // build_runner (>= 2.15) refuses to overwrite pre-existing generated files,
  // so remove the ones shipped with the brick before regenerating.
  const generatedFiles = <String>[
    'lib/core/router/router.gr.dart',
    'lib/i18n/strings.g.dart',
    'lib/i18n/strings_en.g.dart',
    'lib/i18n/strings_es.g.dart',
  ];
  for (final path in generatedFiles) {
    final file = File(path);
    if (file.existsSync()) file.deleteSync();
  }

  // Localization is generated by slang's own CLI (the build_runner integration
  // skips without explicit config).
  if (!await _run(context, 'Generating localization (slang)', 'dart',
      ['run', 'slang'])) {
    return;
  }

  // Routes (auto_route) are generated via build_runner.
  if (!await _run(context, 'Generating routes (build_runner)', 'dart',
      ['run', 'build_runner', 'build'])) {
    return;
  }

  // Tests + coverage are informational; a failure here should not abort
  // generation of an otherwise-valid project.
  await _run(context, 'Running tests', 'flutter', ['test', '--coverage']);

  context.logger.info(
    '''\n\n 🎉 Your Riverpod simple-architecture app is ready!
      \n 🔄 State management: Riverpod 3 (with cache/refresh/debounce/cancel + easyWhen extensions)
      \n 🛣️  Routing: auto_route
      \n 🌐 Networking: Dio (error handler, retry-friendly interceptors, time logging)
      \n 🎨 Theming: flex_color_scheme (light/dark with persistence)
      \n 🗄️  Storage: Hive CE with an encrypted box (key in flutter_secure_storage)
      \n 🌍 Localization: slang (l10n/i18n)
      \n 🚫 Built-in no-internet + locale-picker widgets, responsive_framework, and talker logging
      \n\n 💡 Android note: flutter_secure_storage requires minSdk 23.
      \n 💡 To enable Riverpod lints later, re-add custom_lint + riverpod_lint once the
      \n    analyzer ecosystem realigns, then uncomment the plugin in analysis_options.yaml.
      \n\n Made with ❤️🔥 by Shreeman Arjun — https://shreeman.dev\n\n''',
  );

  context.logger.info('Post generation completed');
}
