import 'dart:io';

import 'package:mason/mason.dart';

/// Runs a command and reports progress, returning whether it succeeded.
Future<bool> _run(
  HookContext context,
  String label,
  String executable,
  List<String> args,
) async {
  final progress = context.logger.progress(label);
  try {
    final result = await Process.run(executable, args, runInShell: true);
    if (result.exitCode == 0) {
      progress.complete('$label — done');
      return true;
    }
    progress.fail('$label — failed (exit ${result.exitCode})');
    context.logger.detail('stdout: ${result.stdout}');
    context.logger.err('stderr: ${result.stderr}');
    return false;
  } catch (e) {
    progress.fail('$label — error: $e');
    return false;
  }
}

void _patchAndroidIdentity(HookContext context) {
  final org = (context.vars['org'] as String?)?.trim() ?? '';
  final name = (context.vars['project_name'] as String?)?.trim() ?? '';
  final title = (context.vars['app_title'] as String?)?.trim() ?? '';
  final snake = name.toLowerCase().replaceAll(RegExp(r'[^a-z0-9_]'), '_');

  // applicationId in build.gradle(.kts), only when org is non-default.
  if (org.isNotEmpty && org != 'com.example' && snake.isNotEmpty) {
    final appId = '$org.$snake';
    for (final p in ['android/app/build.gradle.kts', 'android/app/build.gradle']) {
      final f = File(p);
      if (!f.existsSync()) continue;
      var src = f.readAsStringSync();
      final patched = src.replaceAllMapped(
        RegExp(r'''applicationId\s*=?\s*["'][^"']*["']'''),
        (_) => 'applicationId = "$appId"',
      );
      if (patched != src) {
        f.writeAsStringSync(patched);
        context.logger.detail('Set applicationId to $appId in $p');
      } else {
        context.logger.detail('applicationId pattern not found in $p');
      }
    }
  }

  // android:label in AndroidManifest.xml — scoped to the <application> tag only.
  if (title.isNotEmpty) {
    final f = File('android/app/src/main/AndroidManifest.xml');
    if (!f.existsSync()) {
      context.logger.detail(
          'AndroidManifest.xml not found — skipping android:label patch');
    } else {
      var src = f.readAsStringSync();
      // Match the entire <application ...> opening tag (from <application to the
      // first >) and replace android:label only within that captured block.
      final patched = src.replaceFirstMapped(
        RegExp(r'<application\b[^>]*>', dotAll: true),
        (m) {
          final tag = m.group(0)!;
          final updated = tag.replaceFirst(
            RegExp(r'android:label="[^"]*"'),
            'android:label="$title"',
          );
          return updated;
        },
      );
      if (patched != src) {
        f.writeAsStringSync(patched);
        context.logger.detail('Set android:label to "$title" in AndroidManifest.xml');
      } else {
        context.logger.detail(
            'android:label not found in <application> tag of AndroidManifest.xml');
      }
    }
  }
}

void run(HookContext context) async {
  context.logger.info('Post generation started');

  // When responsive=false, the brick still copies responsive_wrapper.dart
  // (macOS APFS does not allow '/' in filenames, so the Mason conditional-
  // filename trick cannot be used on macOS). Delete the file here instead.
  final responsive = context.vars['responsive'] as bool? ?? false;
  if (!responsive) {
    final wrapperFile =
        File('lib/shared/widget/responsive_wrapper.dart');
    if (wrapperFile.existsSync()) {
      wrapperFile.deleteSync();
      context.logger
          .info('Removed responsive_wrapper.dart (responsive=false)');
    }
  }

  // Dependencies are now pinned in pubspec.yaml, so we only need to resolve
  // them — no `dart pub add` step is required anymore.
  if (!await _run(context, 'Getting packages', 'flutter', ['pub', 'get'])) {
    return;
  }

  // build_runner (>= 2.15) refuses to overwrite pre-existing generated files,
  // so remove the ones shipped with the brick before regenerating.
  const generatedFiles = <String>[
    'lib/core/router/router.gr.dart',
    'lib/i18n/strings.g.dart',
    'lib/i18n/strings_en.g.dart',
    'lib/i18n/strings_es.g.dart',
  ];
  for (final path in generatedFiles) {
    final file = File(path);
    if (file.existsSync()) file.deleteSync();
  }

  // Localization is generated by slang's own CLI (the build_runner integration
  // skips without explicit config).
  if (!await _run(context, 'Generating localization (slang)', 'dart',
      ['run', 'slang'])) {
    return;
  }

  // Routes (auto_route) are generated via build_runner.
  if (!await _run(context, 'Generating routes (build_runner)', 'dart',
      ['run', 'build_runner', 'build'])) {
    return;
  }

  // Tests + coverage are informational; a failure here should not abort
  // generation of an otherwise-valid project.
  await _run(context, 'Running tests', 'flutter', ['test', '--coverage']);

  _patchAndroidIdentity(context);

  final responsiveNote = responsive ? ', responsive_framework' : '';
  context.logger.info(
    '''\n\n 🎉 Your Riverpod simple-architecture app is ready!
      \n 🔄 State management: Riverpod 3 (with cache/refresh/debounce/cancel + easyWhen extensions)
      \n 🛣️  Routing: auto_route
      \n 🌐 Networking: Dio (error handler, retry-friendly interceptors, time logging)
      \n 🎨 Theming: flex_color_scheme (light/dark with persistence)
      \n 🗄️  Storage: Hive CE with an encrypted box (key in flutter_secure_storage)
      \n 🌍 Localization: slang (l10n/i18n)
      \n 🚫 Built-in no-internet + locale-picker widgets$responsiveNote, and talker logging
      \n\n 💡 Android note: flutter_secure_storage requires minSdk 23.
      \n 💡 To enable Riverpod lints later, re-add custom_lint + riverpod_lint once the
      \n    analyzer ecosystem realigns, then uncomment the plugin in analysis_options.yaml.
      \n\n Made with ❤️🔥 by Shreeman Arjun — https://shreeman.dev\n\n''',
  );

  context.logger.info('Post generation completed');
}
